[package]
name = "hyper-header-examples"
version = "0.1.0"
authors = ["Chandler Latour <chandler.latour@gmail.com>"]

[dependencies]
log = "*"
env_logger = "*"

hyper = "*"
# mime = "*"
time = "*"
unicase = "*"
cookie = "*"
